version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: icp-postgres
    environment:
      POSTGRES_DB: icp_builder
      POSTGRES_USER: icp_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - icp-network

  redis:
    image: redis:7-alpine
    container_name: icp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - icp-network

volumes:
  postgres_data:
  redis_data:

networks:
  icp-network:
    driver: bridge
